### ISSUE TITLE
Images des équipements Ping

### ISSUE THREAD

**Issue by aurel-appsthru** [guenneguezt/plugin-ping#2]
Bonjour, 
les équipements Ping n'ont plus d'images. cf PJ. 
Il me semble qu'il manque l'image ping_icon.png dans le dossier "doc\images".
Ou erreur de chemin dans ping.php L.56. 
Cdt. 
Aurel
![2017-11-02 17_05_21-ping - jeedom](https://user-images.githubusercontent.com/1587461/32336700-449d9b7a-bff0-11e7-9b69-520807eb4a3b.png)

**Comment by ghost** [comment]
Corrigé : https://github.com/guenneguezt/plugin-ping/commit/099c14cc579de39c306ffbb3e647d4f83ba4f626
