### ISSUE TITLE
Binding arp-scan to specific interface?

### ISSUE THREAD

**Issue by typhoe** [guenneguezt/plugin-ping#4]
Bonjour,

actuellement, le plugin ne permet pas de spécifier via quelle interface effectuer les commandes arp-scan.

Si plusieurs interfaces sont configurées, arp-scan ne les interroge pas toutes.
Extrait du man: "arp-scan will search the system interface list for the lowest numbered, configured up interface (excluding loopback)."

Est-il envisageable de permettre de spécifier quelle interface utiliser?
Idéalement par périphérique à détecter...  mais sinon, déjà pouvoir modifier la commande arp-scan sur la page de configuration du plugin.

Merci d'avance.

Ex:
`ls /sys/class/net`
`eno1  lo  wlp2s0`

Par defaut
`arp-scan -l -g --retry=5 -t 800 -T XX:XX:XX:XX:XX:XX`
`Interface: wlp2s0, datalink type: EN10MB (Ethernet)`
`Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)`
`0 packets received by filter, 0 packets dropped by kernel`
`Ending arp-scan 1.9: 256 hosts scanned in 11.812 seconds (21.67 hosts/sec). 0 responded`

En forcant l'interface (option -I d'arp-scan)
`arp-scan -I eno1 -l -g --retry=5 -t 800 -T XX:XX:XX:XX:XX:XX`
`Interface: eno1, datalink type: EN10MB (Ethernet)`
`Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)`
`192.168.1.107	XX:XX:XX:XX:XX:XX	(Unknown)`
`2 packets received by filter, 0 packets dropped by kernel`
`Ending arp-scan 1.9: 256 hosts scanned in 11.549 seconds (22.17 hosts/sec). 1 responded`

**Comment by ghost** [comment]
Disponible en version beta

**Comment by typhoe** [comment]
Super, merci beaucoup!

J'ai essayé d'installer le plugin en version beta depuis le market, mais Jeedom ne me propose pour le moment que la version du 22/11 (en gros pas de nouvelle version dispo)... Il y a un truc spécial à faire pour accéder à la beta ou je dois juste attendre qu'elle soit dispo dans Jeedom?
En tout cas, je ferai un retour dès que la nouvelle version est installée sur mon Jeedom.
Et merci encore pour cette réactivité!

**Comment by ghost** [comment]
Pour avoir accès à la Beta, il faut aller sur la page de gestion des plugins cliquer sur le cadi du market, chercher le plugin en question et tu devrais avoir un lien install beta.

A+
Thomas

**Comment by typhoe** [comment]
Ok, donc c'est bien ce que j'ai fait.... 
Il doit y avoir un délai de publication... 
Sur la page de conf du plugin, il m'indique bien que je suis sur la beta "Ping (ping) - beta", mais version 2017-11-22 22:31:15 et version jeedom 1.124.0
Et vérifier les mises à jour ne m'indique rien...
Bref, je vais attendre...
Merci.
